'use client';
import { useEffect, useState } from 'react';
import { AlertTriangle, Check, Loader2, Save, Trash2 } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { createClient } from '@/lib/supabase/client';
import { getPublicProfileUrl } from '@/lib/qard/url';
import { slugSchema } from '@/lib/qard/validation';
import type { Profile } from '@/types/database';

export function SettingsForm({ profile, accountEmail }: { profile: Profile; accountEmail: string }) { const router = useRouter(); const [name, setName] = useState(profile.display_name); const [slug, setSlug] = useState(profile.slug); const [email, setEmail] = useState(accountEmail); const [password, setPassword] = useState(''); const [status, setStatus] = useState(''); const [slugState, setSlugState] = useState(''); const [deleteText, setDeleteText] = useState(''); const changedSlug = slug !== profile.slug;
  useEffect(() => { const timer = setTimeout(async () => { const parsed = slugSchema.safeParse(slug); if (!parsed.success) return setSlugState(parsed.error.issues[0].message); if (parsed.data === profile.slug) return setSlugState('Disponible'); const response = await fetch(`/api/slugs/${encodeURIComponent(parsed.data)}`); const result = await response.json(); setSlugState(result.available ? 'Disponible' : result.error ?? 'Cet identifiant est pris.'); }, 350); return () => clearTimeout(timer); }, [slug, profile.slug]);
  async function saveProfile() { const parsed = slugSchema.safeParse(slug); if (!parsed.success || slugState !== 'Disponible') return setStatus(parsed.success ? slugState : parsed.error.issues[0].message); setStatus('Enregistrement…'); if (parsed.data !== profile.slug) { const response = await fetch('/api/profile/slug', { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ slug: parsed.data }) }); if (!response.ok) return setStatus((await response.json()).error); } const { error } = await createClient().from('qard_profiles').update({ display_name: name.trim() }).eq('id', profile.id); setStatus(error ? error.message : 'Qard enregistrée'); router.refresh(); }
  async function saveAccount() { setStatus('Enregistrement…'); const changes: { email?: string; password?: string } = {}; if (email !== accountEmail) changes.email = email; if (password) changes.password = password; const { error } = await createClient().auth.updateUser(changes); setStatus(error ? error.message : changes.email ? 'Vérifie le nouvel email pour confirmer.' : 'Compte mis à jour'); setPassword(''); }
  async function removeAccount() { if (deleteText !== 'SUPPRIMER') return; setStatus('Suppression…'); const response = await fetch('/api/account', { method: 'DELETE' }); if (!response.ok) return setStatus('Suppression impossible. Reconnecte-toi puis réessaie.'); router.push('/'); router.refresh(); }
  return <div className="settings-stack"><section className="panel settings-section"><h2>Profil public</h2><label>Nom affiché<input value={name} onChange={(e) => setName(e.target.value)} /></label><label>Identifiant<div className="slug-input"><em>@</em><input value={slug} onChange={(e) => setSlug(e.target.value.toLowerCase())} /></div><small className={slugState === 'Disponible' ? 'available' : ''}>{slugState}</small></label><p className="url-preview">{getPublicProfileUrl(slug)}</p>{changedSlug && <div className="warning-box"><AlertTriangle size={18} /><p><strong>Ton URL va changer.</strong> Ton ancien QR pointera vers l’ancienne adresse. Télécharge un nouveau QR après la modification.</p></div>}<button className="button" onClick={saveProfile}><Save size={17} /> Enregistrer le profil</button></section><section className="panel settings-section"><h2>Compte</h2><label>Email de connexion<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} /></label><label>Nouveau mot de passe<input type="password" minLength={8} value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Laisser vide pour ne pas changer" /></label><button className="button button-ghost" onClick={saveAccount}>Mettre à jour le compte</button></section><section className="panel settings-section danger-zone"><h2>Zone sensible</h2><p>Cette action supprime définitivement ton compte, ta Qard, tes liens, tes images et tes analytics.</p><label>Écris SUPPRIMER pour confirmer<input value={deleteText} onChange={(e) => setDeleteText(e.target.value)} /></label><button className="danger-button" onClick={removeAccount} disabled={deleteText !== 'SUPPRIMER'}><Trash2 size={17} /> Supprimer mon compte</button></section>{status && <div className="qard-toast">{status.includes('…') ? <Loader2 className="spin" size={15} /> : <Check size={15} />}{status}</div>}</div>; }
