create extension if not exists pgcrypto;

do $$ begin
  create type public.qard_plan as enum ('free', 'pro');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.subscription_status as enum ('inactive', 'trialing', 'active', 'past_due', 'canceled');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.analytics_event_type as enum ('profile_view', 'link_click', 'contact_download', 'qr_download');
exception when duplicate_object then null;
end $$;

create table if not exists public.qard_profiles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  slug text not null unique check (slug ~ '^[a-z0-9][a-z0-9_-]{2,29}$'),
  display_name text not null check (char_length(display_name) between 1 and 80),
  first_name text,
  last_name text,
  headline text,
  bio text,
  avatar_url text,
  banner_url text,
  company text,
  job_title text,
  location text,
  email_public text,
  phone_public text,
  website text,
  published boolean not null default true,
  show_branding boolean not null default true,
  plan public.qard_plan not null default 'free',
  onboarding_completed boolean not null default false,
  qr_downloaded_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.qard_social_links (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.qard_profiles(id) on delete cascade,
  platform text not null check (platform in ('instagram','snapchat','tiktok','discord','github','youtube','linkedin','x','facebook','twitch','reddit','telegram','whatsapp','spotify','email','phone','website','custom')),
  label text,
  url text not null,
  username text,
  position integer not null default 0 check (position >= 0),
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists qard_social_links_profile_position_idx on public.qard_social_links(profile_id, position);

create table if not exists public.qard_appearance (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null unique references public.qard_profiles(id) on delete cascade,
  theme text not null default 'midnight-glass',
  background_type text not null default 'gradient' check (background_type in ('color','gradient','image')),
  background_value text not null default 'linear-gradient(145deg, #06101f, #0a2850)',
  accent_color text not null default '#8fd4ff',
  text_color text not null default '#f7fbff',
  card_opacity numeric(3,2) not null default 0.78 check (card_opacity between 0.35 and 1),
  card_blur integer not null default 18 check (card_blur between 0 and 32),
  card_radius integer not null default 28 check (card_radius between 0 and 48),
  button_style text not null default 'glass' check (button_style in ('glass','solid','outline','minimal')),
  avatar_shape text not null default 'circle' check (avatar_shape in ('circle','rounded','square')),
  font_family text not null default 'geist' check (font_family in ('geist','inter','serif','mono')),
  animation_style text not null default 'subtle-scale' check (animation_style in ('none','fade','slide','subtle-scale')),
  animation_enabled boolean not null default true,
  show_banner boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.qard_analytics_events (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.qard_profiles(id) on delete cascade,
  social_link_id uuid references public.qard_social_links(id) on delete set null,
  event_type public.analytics_event_type not null,
  referrer text,
  device_type text,
  browser text,
  country text,
  created_at timestamptz not null default now()
);

create index if not exists qard_analytics_events_profile_created_idx on public.qard_analytics_events(profile_id, created_at desc);
create index if not exists qard_analytics_events_profile_type_idx on public.qard_analytics_events(profile_id, event_type, created_at desc);

create table if not exists public.qard_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  plan public.qard_plan not null default 'free',
  status public.subscription_status not null default 'inactive',
  provider text not null default 'stripe',
  provider_customer_id text,
  provider_subscription_id text,
  current_period_end timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.qard_set_updated_at()
returns trigger language plpgsql set search_path = '' as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists qard_profiles_set_updated_at on public.qard_profiles;
drop trigger if exists qard_social_links_set_updated_at on public.qard_social_links;
drop trigger if exists qard_appearance_set_updated_at on public.qard_appearance;
drop trigger if exists qard_subscriptions_set_updated_at on public.qard_subscriptions;
create trigger qard_profiles_set_updated_at before update on public.qard_profiles for each row execute function public.qard_set_updated_at();
create trigger qard_social_links_set_updated_at before update on public.qard_social_links for each row execute function public.qard_set_updated_at();
create trigger qard_appearance_set_updated_at before update on public.qard_appearance for each row execute function public.qard_set_updated_at();
create trigger qard_subscriptions_set_updated_at before update on public.qard_subscriptions for each row execute function public.qard_set_updated_at();

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create or replace function private.handle_qard_new_user()
returns trigger language plpgsql security definer set search_path = '' as $$
declare
  base_slug text;
  generated_slug text;
  qard_profile_id uuid;
begin
  base_slug := coalesce(nullif(trim(both '-' from regexp_replace(lower(split_part(coalesce(new.email, 'qard'), '@', 1)), '[^a-z0-9]+', '-', 'g')), ''), 'qard');
  generated_slug := left(base_slug, 22) || '-' || substr(new.id::text, 1, 6);

  insert into public.qard_profiles (user_id, slug, display_name)
  values (new.id, generated_slug, coalesce(nullif(new.raw_user_meta_data ->> 'display_name', ''), split_part(coalesce(new.email, 'Ma Qard'), '@', 1)))
  on conflict (user_id) do update set user_id = excluded.user_id
  returning id into qard_profile_id;

  insert into public.qard_appearance (profile_id) values (qard_profile_id)
  on conflict (profile_id) do nothing;
  insert into public.qard_subscriptions (user_id) values (new.id)
  on conflict (user_id) do nothing;
  return new;
end;
$$;

revoke all on function private.handle_qard_new_user() from public;
drop trigger if exists on_auth_qard_user_created on auth.users;
create trigger on_auth_qard_user_created after insert on auth.users for each row execute function private.handle_qard_new_user();

insert into public.qard_profiles (user_id, slug, display_name)
select
  id,
  left(coalesce(nullif(trim(both '-' from regexp_replace(lower(split_part(coalesce(email, 'qard'), '@', 1)), '[^a-z0-9]+', '-', 'g')), ''), 'qard'), 22) || '-' || substr(id::text, 1, 6),
  coalesce(nullif(raw_user_meta_data ->> 'display_name', ''), split_part(coalesce(email, 'Ma Qard'), '@', 1))
from auth.users
on conflict (user_id) do nothing;

insert into public.qard_appearance (profile_id)
select id from public.qard_profiles on conflict (profile_id) do nothing;
insert into public.qard_subscriptions (user_id)
select id from auth.users on conflict (user_id) do nothing;

alter table public.qard_profiles enable row level security;
alter table public.qard_social_links enable row level security;
alter table public.qard_appearance enable row level security;
alter table public.qard_analytics_events enable row level security;
alter table public.qard_subscriptions enable row level security;

drop policy if exists "Qard published profiles are public" on public.qard_profiles;
drop policy if exists "Qard users insert their profile" on public.qard_profiles;
drop policy if exists "Qard users update their profile" on public.qard_profiles;
drop policy if exists "Qard users delete their profile" on public.qard_profiles;
create policy "Qard published profiles are public" on public.qard_profiles for select to anon, authenticated using (published or (select auth.uid()) = user_id);
create policy "Qard users insert their profile" on public.qard_profiles for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Qard users update their profile" on public.qard_profiles for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Qard users delete their profile" on public.qard_profiles for delete to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "Qard published links are public" on public.qard_social_links;
drop policy if exists "Qard users insert own links" on public.qard_social_links;
drop policy if exists "Qard users update own links" on public.qard_social_links;
drop policy if exists "Qard users delete own links" on public.qard_social_links;
create policy "Qard published links are public" on public.qard_social_links for select to anon, authenticated using (exists (select 1 from public.qard_profiles p where p.id = profile_id and (p.published or p.user_id = (select auth.uid()))));
create policy "Qard users insert own links" on public.qard_social_links for insert to authenticated with check (exists (select 1 from public.qard_profiles p where p.id = profile_id and p.user_id = (select auth.uid())));
create policy "Qard users update own links" on public.qard_social_links for update to authenticated using (exists (select 1 from public.qard_profiles p where p.id = profile_id and p.user_id = (select auth.uid()))) with check (exists (select 1 from public.qard_profiles p where p.id = profile_id and p.user_id = (select auth.uid())));
create policy "Qard users delete own links" on public.qard_social_links for delete to authenticated using (exists (select 1 from public.qard_profiles p where p.id = profile_id and p.user_id = (select auth.uid())));

drop policy if exists "Qard published appearance is public" on public.qard_appearance;
drop policy if exists "Qard users update own appearance" on public.qard_appearance;
create policy "Qard published appearance is public" on public.qard_appearance for select to anon, authenticated using (exists (select 1 from public.qard_profiles p where p.id = profile_id and (p.published or p.user_id = (select auth.uid()))));
create policy "Qard users update own appearance" on public.qard_appearance for update to authenticated using (exists (select 1 from public.qard_profiles p where p.id = profile_id and p.user_id = (select auth.uid()))) with check (exists (select 1 from public.qard_profiles p where p.id = profile_id and p.user_id = (select auth.uid())));

drop policy if exists "Qard users read own analytics" on public.qard_analytics_events;
drop policy if exists "Qard users record own QR downloads" on public.qard_analytics_events;
create policy "Qard users read own analytics" on public.qard_analytics_events for select to authenticated using (exists (select 1 from public.qard_profiles p where p.id = profile_id and p.user_id = (select auth.uid())));
create policy "Qard users record own QR downloads" on public.qard_analytics_events for insert to authenticated with check (event_type = 'qr_download' and exists (select 1 from public.qard_profiles p where p.id = profile_id and p.user_id = (select auth.uid())));

drop policy if exists "Qard users read own subscription" on public.qard_subscriptions;
create policy "Qard users read own subscription" on public.qard_subscriptions for select to authenticated using ((select auth.uid()) = user_id);

grant usage on schema public to anon, authenticated;
grant select (id, slug, display_name, first_name, last_name, headline, bio, avatar_url, banner_url, company, job_title, location, email_public, phone_public, website, published, show_branding, created_at, updated_at) on public.qard_profiles to anon;
grant select on public.qard_social_links, public.qard_appearance to anon;
grant select, insert, update, delete on public.qard_profiles, public.qard_social_links to authenticated;
grant select, update on public.qard_appearance to authenticated;
grant select, insert on public.qard_analytics_events to authenticated;
grant select on public.qard_subscriptions to authenticated;
grant usage, select on sequence public.qard_analytics_events_id_seq to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('avatars', 'avatars', true, 5242880, array['image/jpeg','image/png','image/webp']),
  ('banners', 'banners', true, 8388608, array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Qard public profile images are readable" on storage.objects;
drop policy if exists "Qard users upload profile images" on storage.objects;
drop policy if exists "Qard users update profile images" on storage.objects;
drop policy if exists "Qard users delete profile images" on storage.objects;
create policy "Qard public profile images are readable" on storage.objects for select to anon, authenticated using (bucket_id in ('avatars', 'banners'));
create policy "Qard users upload profile images" on storage.objects for insert to authenticated with check (bucket_id in ('avatars', 'banners') and (storage.foldername(name))[1] = (select auth.uid())::text);
create policy "Qard users update profile images" on storage.objects for update to authenticated using (bucket_id in ('avatars', 'banners') and owner_id = (select auth.uid())::text) with check (bucket_id in ('avatars', 'banners') and (storage.foldername(name))[1] = (select auth.uid())::text);
create policy "Qard users delete profile images" on storage.objects for delete to authenticated using (bucket_id in ('avatars', 'banners') and owner_id = (select auth.uid())::text);
